language: python
python:
 - "2.6"
 - "2.7"
 - "pypy"
install: "pip install -r requirements.txt -r test-requirements.txt"
script: "nosetests -i '^(it|ensure|must|should|specs?|examples?|tests?)' --with-spec --spec-color"
